<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $managerList = [[
            'id' => 1,
            'full_name' => "admin超级管理员",
            'account' => "admin",
            'password' => "b4b47762ff03b233ee902c996e9a0cc9",
            'entry_password' => "123456",
            'email' => "123@qq.com",
            'salt' => "c2DWJV",
            'last_ip' => "",
        ],[
            'id' => 2,
            'full_name' => "测试管理员",
            'account' => "test",
            'password' => "b4b47762ff03b233ee902c996e9a0cc9",
            'entry_password' => "123456",
            'email' => "test@qq.com",
            'salt' => "c2DWJV",
            'last_ip' => "",
        ]];

        foreach ($managerList as $arr) {
            \App\Models\Admin\Manager::factory()->create($arr);
        }

        \App\Models\Admin\Branch::factory()->create([
            'id' => 1,
            'branch_name' => "某某公司",
            'type' => 1,
            'orders' => 0,
            'parent_id' => 0,
        ]);

        $managerRoleList = [
            ['manager_id' => 2,'role_id' => 1],
            ['manager_id' => 2,'role_id' => 2],
            ['manager_id' => 2,'role_id' => 3],
            ['manager_id' => 2,'role_id' => 4],
            ['manager_id' => 2,'role_id' => 5],
            ['manager_id' => 2,'role_id' => 6],
        ];
        foreach ($managerRoleList as $arr) {
            \App\Models\Admin\ManagerRole::factory()->create($arr);
        }

        $roleList = [[
            'id' => 1,
            'role_name' => '管理员',
            'status' => 1,
            'is_cate' => 1,
            'orders' => 0,
            'remark' => '',
            'parent_id' => 0,
        ],[
            'id' => 2,
            'role_name' => '测试员',
            'status' => 1,
            'is_cate' => 0,
            'orders' => 0,
            'remark' => '',
            'parent_id' => 1,
        ]];
        foreach ($roleList as $arr) {
            \App\Models\Admin\Role::factory()->create($arr);
        }

        $rolePrivilegeList = [
            ['role_id' => 1,'privilege_id' => 1],
            ['role_id' => 1,'privilege_id' => 2],
            ['role_id' => 1,'privilege_id' => 3],
            ['role_id' => 1,'privilege_id' => 4],
            ['role_id' => 1,'privilege_id' => 5],
            ['role_id' => 1,'privilege_id' => 6]
        ];
        foreach ($rolePrivilegeList as $arr) {
            \App\Models\Admin\RolePrivilege::factory()->create($arr);
        }

        $privilegeList = [[
            'id' => 1,
            'privilege_name' => '常规管理',
            'module_name' => '#',
            'controller_name' => '#',
            'action_name' => '#',
            'route_url' => '#',
            'route_name' => '#',
            'parameter' => '',
            'privilege_icon' => '',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 1,
            'parent_id' => 0,
        ],[
            'id' => 2,
            'privilege_name' => '权限管理',
            'module_name' => '#',
            'controller_name' => '#',
            'action_name' => '#',
            'route_url' => '#',
            'route_name' => '#',
            'parameter' => '',
            'privilege_icon' => 'layui-icon-flag',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 1,
            'parent_id' => 1,
        ],[
            'id' => 3,
            'privilege_name' => '系统配置',
            'module_name' => 'admin',
            'controller_name' => 'AdminController',
            'action_name' => 'system',
            'route_url' => '/admin/system_config',
            'route_name' => 'systemConfig',
            'parameter' => '',
            'privilege_icon' => 'fa-calendar',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 1,
            'parent_id' => 2,
        ],[
            'id' => 4,
            'privilege_name' => '菜单管理',
            'module_name' => 'admin',
            'controller_name' => 'PrivilegeController',
            'action_name' => 'index',
            'route_url' => '/admin/privilege_list',
            'route_name' => 'privilegeList',
            'parameter' => '',
            'privilege_icon' => 'fa-align-justify',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 1,
            'parent_id' => 2,
        ],[
            'id' => 5,
            'privilege_name' => '角色管理',
            'module_name' => 'admin',
            'controller_name' => 'RoleController',
            'action_name' => 'index',
            'route_url' => '/admin/role_list',
            'route_name' => 'roleList',
            'parameter' => '',
            'privilege_icon' => 'fa-drivers-license',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 1,
            'parent_id' => 2,
        ],[
            'id' => 6,
            'privilege_name' => '管理员',
            'module_name' => 'admin',
            'controller_name' => 'ManagerController',
            'action_name' => 'index',
            'route_url' => '/admin/manager_list',
            'route_name' => 'mangerList',
            'parameter' => '',
            'privilege_icon' => 'fa-institution',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 1,
            'parent_id' => 2,
        ],[
            'id' => 7,
            'privilege_name' => '日志管理',
            'module_name' => '#',
            'controller_name' => '#',
            'action_name' => '#',
            'route_url' => '#',
            'route_name' => '#',
            'parameter' => '',
            'privilege_icon' => 'layui-icon-note',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 1,
            'parent_id' => 1,
        ],[
            'privilege_name' => '新增菜单',
            'module_name' => 'admin',
            'controller_name' => 'PrivilegeController',
            'action_name' => 'create',
            'route_url' => '/admin/privilege_add',
            'route_name' => 'privilegeAdd',
            'parameter' => '',
            'privilege_icon' => '',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 0,
            'parent_id' => 4,
        ],[
            'privilege_name' => '编辑菜单',
            'module_name' => 'admin',
            'controller_name' => 'PrivilegeController',
            'action_name' => 'update',
            'route_url' => '/admin/privilege_edit',
            'route_name' => 'privilegeEdit',
            'parameter' => '',
            'privilege_icon' => '',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 0,
            'parent_id' => 4,
        ],[
            'privilege_name' => '删除菜单',
            'module_name' => 'admin',
            'controller_name' => 'PrivilegeController',
            'action_name' => 'delete',
            'route_url' => '/admin/privilege_del',
            'route_name' => 'privilegeDelete',
            'parameter' => '',
            'privilege_icon' => 'fa-align-justify',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 0,
            'parent_id' => 4,
        ],[
            'privilege_name' => '新增角色',
            'module_name' => 'admin',
            'controller_name' => 'RoleController',
            'action_name' => 'create',
            'route_url' => '/admin/role_add',
            'route_name' => 'roleAdd',
            'parameter' => '',
            'privilege_icon' => '',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 0,
            'parent_id' => 5,
        ],[
            'privilege_name' => '编辑角色',
            'module_name' => 'admin',
            'controller_name' => 'RoleController',
            'action_name' => 'update',
            'route_url' => '/admin/role_edit',
            'route_name' => 'RoleEdit',
            'parameter' => '',
            'privilege_icon' => '',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 0,
            'parent_id' => 5,
        ],[
            'privilege_name' => '角色授权',
            'module_name' => 'admin',
            'controller_name' => 'RoleController',
            'action_name' => 'authorize',
            'route_url' => '/admin/role_authorize',
            'route_name' => 'roleAuthorize',
            'parameter' => '',
            'privilege_icon' => '',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 0,
            'parent_id' => 5,
        ],[
            'privilege_name' => '删除角色',
            'module_name' => 'admin',
            'controller_name' => 'RoleController',
            'action_name' => 'delete',
            'route_url' => '/admin/role_del',
            'route_name' => 'roleDelete',
            'parameter' => '',
            'privilege_icon' => '',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 0,
            'parent_id' => 5,
        ],[
            'privilege_name' => '新增管理员',
            'module_name' => 'admin',
            'controller_name' => 'ManagerController',
            'action_name' => 'create',
            'route_url' => '/admin/manager_add',
            'route_name' => 'managerAdd',
            'parameter' => '',
            'privilege_icon' => '',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 0,
            'parent_id' => 6,
        ],[
            'privilege_name' => '编辑管理员',
            'module_name' => 'admin',
            'controller_name' => 'ManagerController',
            'action_name' => 'update',
            'route_url' => '/admin/manager_edit',
            'route_name' => 'managerEdit',
            'parameter' => '',
            'privilege_icon' => '',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 0,
            'parent_id' => 6,
        ],[
            'privilege_name' => '删除管理员',
            'module_name' => 'admin',
            'controller_name' => 'ManagerController',
            'action_name' => 'delete',
            'route_url' => '/admin/manager_del',
            'route_name' => 'managerDelete',
            'parameter' => '',
            'privilege_icon' => '',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 0,
            'parent_id' => 6,
        ],[
            'privilege_name' => '操作日志',
            'module_name' => 'admin',
            'controller_name' => 'LogController',
            'action_name' => 'sysOperateLog',
            'route_url' => '/admin/sys_operate_log',
            'route_name' => 'sysOperateLog',
            'parameter' => '',
            'privilege_icon' => 'fa-paw',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 1,
            'parent_id' => 7,
        ],[
            'privilege_name' => '登录日志',
            'module_name' => 'admin',
            'controller_name' => 'LogController',
            'action_name' => 'sysLoginLog',
            'route_url' => '/admin/sys_login_log',
            'route_name' => 'sysLoginLog',
            'parameter' => '',
            'privilege_icon' => 'fa-paw',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 1,
            'parent_id' => 7,
        ],[
            'privilege_name' => '删除操作日志',
            'module_name' => 'admin',
            'controller_name' => 'LogController',
            'action_name' => 'deleteSysOperateLog',
            'route_url' => '/admin/del_operate_log',
            'route_name' => 'deleteSysOperateLog',
            'parameter' => '',
            'privilege_icon' => '',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 0,
            'parent_id' => 7,
        ],[
            'privilege_name' => '删除登录日志',
            'module_name' => 'admin',
            'controller_name' => 'LogController',
            'action_name' => 'deleteSysLoginLog',
            'route_url' => '/admin/del_login_log',
            'route_name' => 'deleteSysLoginLog',
            'parameter' => '',
            'privilege_icon' => '',
            'target' => '_self',
            'orders' => 0,
            'is_menu' => 0,
            'parent_id' => 7,
        ]];

        foreach ($privilegeList as $arr) {
            \App\Models\Admin\Privilege::factory()->create($arr);
        }
    }
}
